In [1]:
# importing libraries

import pandas as pd

## Single-page Tabular Scrape

- <a href="https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AllRecordsAction.action">On this site</a>, scrape all the doctors info on page 292.
- Export the content into a CSV file called ```page_292.csv```.

In [2]:
## create coding cells as needed

url_sp = "https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AllRecordsAction.action?d-49653-p="
page_num = 292

pd.read_html(f"{url_sp}{page_num}")

[                                  Physician Last Name  \
 0                                              Feiner
 1                                              Taylor
 2                                             Donshik
 3                                             Robbins
 4                                             Freeman
 5                                           Markowitz
 6                                              Puskas
 7                                               Lopez
 8                                              Hirsch
 9                                              Stobie
 10                                                Leo
 11                                                 Lu
 12                                              James
 13                                             O'Hair
 14                                           Berselli
 15                                             Baldeo
 16                                       Bell-Thomson
 17                                        Vanderwalde
 18                                            Salerno
 19                                            Frumkin
 20                               New Physician Search
 21  Physician Records \tvar css = ".visualping-con...

                                  Physician First Name Physician Middle Name  \
 0                                                Marc                  Alan
 1                                               David               Howarth
 2                                                 Jon                 David
 3                                             Richard                 Gregg
 4                                             Douglas                   NaN
 5                                              Howard                   NaN
 6                                                John               Michael
 7                                                Jose                     A
 8                                             Anthony                   NaN
 9                                               David                     W
 10                                             Thomas        Friedrich Paul
 11                                              Jiade                   Jay
 12                                             Robert               Truxton
 13                                              James               Patrick
 14                                             Robert                Andrew
 15                                             Philip                   NaN
 16                                               John                   NaN
 17                                               Alan                   NaN
 18                                             Egisto                   NaN
 19                                                Eli                     A
 20                                                NaN                   NaN
 21  Physician Last Name Physician First Name Physi...                   NaN

     License Number License Type Effective Date Date Updated  Year of Birth
 0         147174.0           MD     10/10/2003   10/06/2003         1952.0
 1         154079.0           MD     10/10/2003   10/06/2003         1953.0
 2         202926.0           MD     10/10/2003   10/06/2003         1968.0
 3         179378.0           MD     10/10/2003   10/06/2003         1963.0
 4         220267.0           MD     10/10/2003   10/06/2003         1968.0
 5         188933.0           MD     10/10/2003   10/06/2003         1961.0
 6         120273.0           MD     10/06/2003   10/01/2003         1945.0
 7         192852.0           MD     10/06/2003   10/01/2003         1962.0
 8          98440.0           MD     10/01/2003   09/24/2003         1940.0
 9           2800.0           PA     10/01/2003   09/24/2003         1962.0
 10         79593.0           MD     10/01/2003   09/24/2003         1925.0
 11        213593.0           MD     10/01/2003   09/24/2003         1970.0
 12        185183.0           MD     10/01/2003   09/24/2003         1932.0
 13        200465.0           MD     10/01/2003   09/24/2003         1965.0
 14         95088.0           MD     10/10/2003   09/22/2003         1939.0
 15        194531.0           MD     06/28/2004   09/22/2003         1957.0
 16        121353.0           MD     12/02/1998   09/17/2003         1947.0
 17        132894.0           MD     09/07/2003   09/16/2003         1949.0
 18        153248.0           MD     09/18/2003   09/12/2003         1944.0
 19        108456.0           MD     09/18/2003   09/12/2003         1936.0
 20             NaN          NaN            NaN          NaN            NaN
 21             NaN          NaN            NaN          NaN            NaN  ,
    Physician Last Name Physician First Name Physician Middle Name  \
 0               Feiner                 Marc                  Alan
 1               Taylor                David               Howarth
 2              Donshik                  Jon                 David
 3              Robbins              Richard                 Gregg
 4              Freeman              Douglas                   NaN
 5            Markowitz               Howard                   NaN
 6               Puskas                 John               Michael
 7                Lopez                 Jose                     A
 8               Hirsch              Anthony                   NaN
 9               Stobie                David                     W
 10                 Leo               Thomas        Friedrich Paul
 11                  Lu                Jiade                   Jay
 12               James               Robert               Truxton
 13              O'Hair                James               Patrick
 14            Berselli               Robert                Andrew
 15              Baldeo               Philip                   NaN
 16        Bell-Thomson                 John                   NaN
 17         Vanderwalde                 Alan                   NaN
 18             Salerno               Egisto                   NaN
 19             Frumkin                  Eli                     A

     License Number License Type Effective Date Date Updated  Year of Birth
 0           147174           MD     10/10/2003   10/06/2003           1952
 1           154079           MD     10/10/2003   10/06/2003           1953
 2           202926           MD     10/10/2003   10/06/2003           1968
 3           179378           MD     10/10/2003   10/06/2003           1963
 4           220267           MD     10/10/2003   10/06/2003           1968
 5           188933           MD     10/10/2003   10/06/2003           1961
 6           120273           MD     10/06/2003   10/01/2003           1945
 7           192852           MD     10/06/2003   10/01/2003           1962
 8            98440           MD     10/01/2003   09/24/2003           1940
 9             2800           PA     10/01/2003   09/24/2003           1962
 10           79593           MD     10/01/2003   09/24/2003           1925
 11          213593           MD     10/01/2003   09/24/2003           1970
 12          185183           MD     10/01/2003   09/24/2003           1932
 13          200465           MD     10/01/2003   09/24/2003           1965
 14           95088           MD     10/10/2003   09/22/2003           1939
 15          194531           MD     06/28/2004   09/22/2003           1957
 16          121353           MD     12/02/1998   09/17/2003           1947
 17          132894           MD     09/07/2003   09/16/2003           1949
 18          153248           MD     09/18/2003   09/12/2003           1944
 19          108456           MD     09/18/2003   09/12/2003           1936  ,
     0                                                  1
 0 NaN  A B C D E F G H I J K L M N O P Q R S T U V W ...,
    0  1  2  3  4  5  6  7  8  9   ... 17 18 19 20 21 22 23 24 25 26
 0 NaN  A  B  C  D  E  F  G  H  I  ...  Q  R  S  T  U  V  W  X  Y  Z

 [1 rows x 27 columns]]

In [3]:
response_sp = pd.read_html(f"{url_sp}{page_num}")[1]
response_sp

,Physician Last Name,Physician First Name,Physician Middle Name,License Number,License Type,Effective Date,Date Updated,Year of Birth
0,Feiner,Marc,Alan,147174,MD,10/10/2003,10/06/2003,1952
1,Taylor,David,Howarth,154079,MD,10/10/2003,10/06/2003,1953
2,Donshik,Jon,David,202926,MD,10/10/2003,10/06/2003,1968
3,Robbins,Richard,Gregg,179378,MD,10/10/2003,10/06/2003,1963
4,Freeman,Douglas,NaN,220267,MD,10/10/2003,10/06/2003,1968
5,Markowitz,Howard,NaN,188933,MD,10/10/2003,10/06/2003,1961
6,Puskas,John,Michael,120273,MD,10/06/2003,10/01/2003,1945
7,Lopez,Jose,A,192852,MD,10/06/2003,10/01/2003,1962
8,Hirsch,Anthony,NaN,98440,MD,10/01/2003,09/24/2003,1940
9,Stobie,David,W,2800,PA,10/01/2003,09/24/2003,1962
10,Leo,Thomas,Friedrich Paul,79593,MD,10/01/2003,09/24/2003,1925
11,Lu,Jiade,Jay,213593,MD,10/01/2003,09/24/2003,1970
12,James,Robert,Truxton,185183,MD,10/01/2003,09/24/2003,1932
13,O'Hair,James,Patrick,200465,MD,10/01/2003,09/24/2003,1965
14,Berselli,Robert,Andrew,95088,MD,10/10/2003,09/22/2003,1939
15,Baldeo,Philip,NaN,194531,MD,06/28/2004,09/22/2003,1957
16,Bell-Thomson,John,NaN,121353,MD,12/02/1998,09/17/2003,1947
17,Vanderwalde,Alan,NaN,132894,MD,09/07/2003,09/16/2003,1949
18,Salerno,Egisto,NaN,153248,MD,09/18/2003,09/12/2003,1944
19,Frumkin,Eli,A,108456,MD,09/18/2003,09/12/2003,1936

In [4]:
response_sp.to_csv("page_292.csv", index=False, encoding="UTF-8")

## Multipage Tabular Scrape

- <a href="https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AllRecordsAction.action">On this site</a>, scrape all doctors whose last names begin with "P".
- Export the content into a CSV file called ```md_P.csv```.

In [5]:
## create coding cells as needed

url_mp = "https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch="
letter_search = "P"

pd.read_html(f"{url_mp}{letter_search}")

[                                  Physician Last Name  \
 0                                                Paal
 1                                                Pace
 2                                                Pace
 3                                             Pacetti
 4                                              Pachas
 5                                             Pacheco
 6                                               Pacik
 7                                               Pacis
 8                                                Pack
 9                                        Packianathan
 10                                       Packianathan
 11                                              Padeh
 12                                              Padeh
 13                                            Padilla
 14                                            Padilla
 15                                            Padilla
 16                                            Padnani
 17                                             Paduch
 18                                             Pagano
 19                                             Pagano
 20                               New Physician Search
 21  Physician Records \tvar css = ".visualping-con...

                                  Physician First Name Physician Middle Name  \
 0                                                Adam                   NaN
 1                                              Enrico                   NaN
 2                                             Leonard                   NaN
 3                                             Stephen                     J
 4                                              Hector                     M
 5                                               Denny                    J.
 6                                               Peter                   NaN
 7                                           Andresito                    B.
 8                                                   A               Stephen
 9                                            Emmanuel                   NaN
 10                                           Emmanuel                   NaN
 11                                              Asher                   NaN
 12                                              Asher                   NaN
 13                                          Crisologo                   NaN
 14                                              Maria             Lourdes B
 15                                              Maria                   NaN
 16                                              Koshi                   NaN
 17                                             Darius                  Adam
 18                                            Anthony                   NaN
 19                                             Dwight                     M
 20                                                NaN                   NaN
 21  Physician Last Name Physician First Name Physi...                   NaN

     License Number License Type Effective Date Date Updated  Year of Birth
 0              NaN           MD     10/30/2000          NaN         1961.0
 1         166026.0           MD     08/21/2001          NaN         1956.0
 2         172870.0           MD     01/15/2002   01/22/2002         1952.0
 3         175021.0           MD     04/14/2016   04/07/2016         1957.0
 4          95535.0           MD     02/11/1993          NaN            NaN
 5         258600.0           DO     08/27/2020   08/26/2020         1962.0
 6          96944.0           MD     11/15/2012   11/09/2012         1940.0
 7         125213.0           MD     10/22/2021   10/22/2021         1938.0
 8         183669.0           MD     04/28/2000   07/19/2001         1956.0
 9         203833.0           MD     07/31/2008   07/25/2008         1945.0
 10        203833.0           MD     07/15/2016   07/18/2016         1946.0
 11        108572.0           MD     04/18/1997          NaN            NaN
 12        108572.0           MD     07/10/1995          NaN            NaN
 13        109998.0           MD     10/08/2002   04/05/2011         1935.0
 14        148379.0           MD     09/13/2001   10/15/2001         1951.0
 15        191849.0           MD     04/20/2011   04/18/2011         1962.0
 16        159535.0           MD     05/19/1993   03/22/2004            NaN
 17        227386.0           MD     09/05/2023   08/29/2023         1967.0
 18         80588.0           MD     11/12/1997          NaN            NaN
 19        141105.0           MD     06/09/2004   06/04/2004         1952.0
 20             NaN          NaN            NaN          NaN            NaN
 21             NaN          NaN            NaN          NaN            NaN  ,
    Physician Last Name Physician First Name Physician Middle Name  \
 0                 Paal                 Adam                   NaN
 1                 Pace               Enrico                   NaN
 2                 Pace              Leonard                   NaN
 3              Pacetti              Stephen                     J
 4               Pachas               Hector                     M
 5              Pacheco                Denny                    J.
 6                Pacik                Peter                   NaN
 7                Pacis            Andresito                    B.
 8                 Pack                    A               Stephen
 9         Packianathan             Emmanuel                   NaN
 10        Packianathan             Emmanuel                   NaN
 11               Padeh                Asher                   NaN
 12               Padeh                Asher                   NaN
 13             Padilla            Crisologo                   NaN
 14             Padilla                Maria             Lourdes B
 15             Padilla                Maria                   NaN
 16             Padnani                Koshi                   NaN
 17              Paduch               Darius                  Adam
 18              Pagano              Anthony                   NaN
 19              Pagano               Dwight                     M

     License Number License Type Effective Date Date Updated  Year of Birth
 0              NaN           MD     10/30/2000          NaN         1961.0
 1         166026.0           MD     08/21/2001          NaN         1956.0
 2         172870.0           MD     01/15/2002   01/22/2002         1952.0
 3         175021.0           MD     04/14/2016   04/07/2016         1957.0
 4          95535.0           MD     02/11/1993          NaN            NaN
 5         258600.0           DO     08/27/2020   08/26/2020         1962.0
 6          96944.0           MD     11/15/2012   11/09/2012         1940.0
 7         125213.0           MD     10/22/2021   10/22/2021         1938.0
 8         183669.0           MD     04/28/2000   07/19/2001         1956.0
 9         203833.0           MD     07/31/2008   07/25/2008         1945.0
 10        203833.0           MD     07/15/2016   07/18/2016         1946.0
 11        108572.0           MD     04/18/1997          NaN            NaN
 12        108572.0           MD     07/10/1995          NaN            NaN
 13        109998.0           MD     10/08/2002   04/05/2011         1935.0
 14        148379.0           MD     09/13/2001   10/15/2001         1951.0
 15        191849.0           MD     04/20/2011   04/18/2011         1962.0
 16        159535.0           MD     05/19/1993   03/22/2004            NaN
 17        227386.0           MD     09/05/2023   08/29/2023         1967.0
 18         80588.0           MD     11/12/1997          NaN            NaN
 19        141105.0           MD     06/09/2004   06/04/2004         1952.0  ,
     0                                                  1
 0 NaN  A B C D E F G H I J K L M N O P Q R S T U V W ...,
    0  1  2  3  4  5  6  7  8  9   ... 17 18 19 20 21 22 23 24 25 26
 0 NaN  A  B  C  D  E  F  G  H  I  ...  Q  R  S  T  U  V  W  X  Y  Z

 [1 rows x 27 columns]]

In [6]:
response_mp = pd.read_html(f"{url_mp}{letter_search}")[1]
response_mp

,Physician Last Name,Physician First Name,Physician Middle Name,License Number,License Type,Effective Date,Date Updated,Year of Birth
0,Paal,Adam,NaN,NaN,MD,10/30/2000,NaN,1961.0
1,Pace,Enrico,NaN,166026.0,MD,08/21/2001,NaN,1956.0
2,Pace,Leonard,NaN,172870.0,MD,01/15/2002,01/22/2002,1952.0
3,Pacetti,Stephen,J,175021.0,MD,04/14/2016,04/07/2016,1957.0
4,Pachas,Hector,M,95535.0,MD,02/11/1993,NaN,NaN
5,Pacheco,Denny,J.,258600.0,DO,08/27/2020,08/26/2020,1962.0
6,Pacik,Peter,NaN,96944.0,MD,11/15/2012,11/09/2012,1940.0
7,Pacis,Andresito,B.,125213.0,MD,10/22/2021,10/22/2021,1938.0
8,Pack,A,Stephen,183669.0,MD,04/28/2000,07/19/2001,1956.0
9,Packianathan,Emmanuel,NaN,203833.0,MD,07/31/2008,07/25/2008,1945.0
10,Packianathan,Emmanuel,NaN,203833.0,MD,07/15/2016,07/18/2016,1946.0
11,Padeh,Asher,NaN,108572.0,MD,04/18/1997,NaN,NaN
12,Padeh,Asher,NaN,108572.0,MD,07/10/1995,NaN,NaN
13,Padilla,Crisologo,NaN,109998.0,MD,10/08/2002,04/05/2011,1935.0
14,Padilla,Maria,Lourdes B,148379.0,MD,09/13/2001,10/15/2001,1951.0
15,Padilla,Maria,NaN,191849.0,MD,04/20/2011,04/18/2011,1962.0
16,Padnani,Koshi,NaN,159535.0,MD,05/19/1993,03/22/2004,NaN
17,Paduch,Darius,Adam,227386.0,MD,09/05/2023,08/29/2023,1967.0
18,Pagano,Anthony,NaN,80588.0,MD,11/12/1997,NaN,NaN
19,Pagano,Dwight,M,141105.0,MD,06/09/2004,06/04/2004,1952.0

In [7]:
response_mp.to_csv("md_p.csv", index=False, encoding="UTF-8")